let plan = null;
let currentLessonIndex = null;
let conversation = [];

// ----- Voice state -----
let voiceModeEnabled = false;
let speechRecognition = null;
let isListening = false;

const supportsSpeechRecognition =
  "SpeechRecognition" in window || "webkitSpeechRecognition" in window;
const supportsSpeechSynthesis = "speechSynthesis" in window;

// ----- DOM refs -----
const builderForm = document.getElementById("builder-form");
const topicInput = document.getElementById("topic");
const levelSelect = document.getElementById("level");
const toneSelect = document.getElementById("tone");
const goalInput = document.getElementById("goal");
const generateBtn = document.getElementById("generate-btn");
const builderStatus = document.getElementById("builder-status");

const mainSection = document.getElementById("main");

const courseTitleEl = document.getElementById("course-title");
const courseDescEl = document.getElementById("course-description");
const courseTopicEl = document.getElementById("course-topic");
const courseLevelEl = document.getElementById("course-level");
const courseGoalEl = document.getElementById("course-goal");
const courseToneEl = document.getElementById("course-tone");

const lessonsListEl = document.getElementById("lessons-list");

const lessonTitleEl = document.getElementById("lesson-title");
const lessonSummaryEl = document.getElementById("lesson-summary");
const lessonKeypointsEl = document.getElementById("lesson-keypoints");

const quizButton = document.getElementById("quiz-button");
const quizContentEl = document.getElementById("quiz-content");

const chatMessagesEl = document.getElementById("chat-messages");
const chatForm = document.getElementById("chat-form");
const chatInput = document.getElementById("chat-input");
const chatSendBtn = document.getElementById("chat-send");

// voice controls
const micButton = document.getElementById("mic-button");
const voiceModeToggle = document.getElementById("voice-mode-toggle");

/* Helpers */

function setBuilderStatus(text, isError = false) {
  builderStatus.textContent = text || "";
  builderStatus.style.color = isError ? "var(--danger)" : "var(--text-muted)";
}

function clearElement(el) {
  while (el.firstChild) el.removeChild(el.firstChild);
}

function addChatMessage(role, text) {
  const div = document.createElement("div");
  div.className = `chat-message ${role}`;
  div.textContent = text;
  chatMessagesEl.appendChild(div);
  chatMessagesEl.scrollTop = chatMessagesEl.scrollHeight;
}

/* Voice helpers */

function speak(text) {
  if (!voiceModeEnabled || !supportsSpeechSynthesis) return;
  if (!text) return;
  try {
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = "en-US";
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  } catch (e) {
    console.warn("speechSynthesis error:", e);
  }
}

function initSpeechRecognition() {
  if (!supportsSpeechRecognition) return null;
  if (speechRecognition) return speechRecognition;

  const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
  const recog = new SR();
  recog.lang = "en-US";
  recog.interimResults = false;
  recog.maxAlternatives = 1;

  recog.onstart = () => {
    isListening = true;
    if (micButton) {
      micButton.classList.add("listening");
      micButton.textContent = "Listening...";
    }
  };

  recog.onend = () => {
    isListening = false;
    if (micButton) {
      micButton.classList.remove("listening");
      micButton.textContent = "Mic";
    }
  };

  recog.onerror = (event) => {
    console.error("Speech recognition error:", event.error);
  };

  recog.onresult = (event) => {
    const transcript = event.results[0][0].transcript;
    if (!transcript) return;
    chatInput.value = transcript;
    // Auto-send the question
    sendChatMessage();
  };

  speechRecognition = recog;
  return recog;
}

function toggleListening() {
  if (!voiceModeEnabled) return;
  const recog = initSpeechRecognition();
  if (!recog) {
    alert("Voice input is not supported in this browser. Try Chrome.");
    return;
  }
  try {
    if (isListening) {
      recog.stop();
    } else {
      if (supportsSpeechSynthesis) {
        window.speechSynthesis.cancel();
      }
      recog.start();
    }
  } catch (e) {
    console.warn("Error toggling speech recognition:", e);
  }
}

/* UI renderers */

function resetChatWithGreeting() {
  clearElement(chatMessagesEl);
  conversation = [];

  if (!plan) return;

  const greeting = `Hi! I'm your ${
    plan.tone || "AI"
  } tutor for "${plan.title}". Start by picking a lesson on the left, or ask me anything about ${plan.topic}.`;
  addChatMessage("assistant", greeting);
  conversation.push({ role: "assistant", content: greeting });
  speak(greeting);
}

function renderPlan() {
  if (!plan) return;

  courseTitleEl.textContent = plan.title || "Generated course";
  courseDescEl.textContent =
    plan.description || "A short mini-course generated by the AI.";
  courseTopicEl.textContent = plan.topic ? `Topic: ${plan.topic}` : "";
  courseLevelEl.textContent = plan.level ? `Level: ${plan.level}` : "";
  courseGoalEl.textContent = plan.goal ? `Goal: ${plan.goal}` : "";
  courseToneEl.textContent = plan.tone ? `Tone: ${plan.tone}` : "";

  clearElement(lessonsListEl);

  if (!Array.isArray(plan.lessons) || plan.lessons.length === 0) {
    const p = document.createElement("p");
    p.className = "muted small";
    p.textContent = "No lessons generated.";
    lessonsListEl.appendChild(p);
  } else {
    plan.lessons.forEach((lesson, idx) => {
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = "lesson-item";
      btn.dataset.index = idx;

      const titleSpan = document.createElement("span");
      titleSpan.className = "lesson-title";
      titleSpan.textContent = lesson.title || `Lesson ${idx + 1}`;

      const subSpan = document.createElement("span");
      subSpan.className = "lesson-sub";
      subSpan.textContent =
        (lesson.summary || "").slice(0, 100) +
        (lesson.summary && lesson.summary.length > 100 ? "..." : "");

      btn.appendChild(titleSpan);
      btn.appendChild(subSpan);

      btn.addEventListener("click", () => selectLesson(idx));
      lessonsListEl.appendChild(btn);
    });

    selectLesson(0);
  }

  quizButton.disabled = !plan.lessons || plan.lessons.length === 0;

  mainSection.classList.remove("hidden");
  resetChatWithGreeting();
}

function selectLesson(index) {
  if (!plan || !Array.isArray(plan.lessons)) return;
  const lesson = plan.lessons[index];
  if (!lesson) return;

  currentLessonIndex = index;

  const lessonButtons = lessonsListEl.querySelectorAll(".lesson-item");
  lessonButtons.forEach((btn) => {
    const i = Number(btn.dataset.index);
    btn.classList.toggle("active", i === index);
  });

  lessonTitleEl.textContent = lesson.title || `Lesson ${index + 1}`;
  lessonSummaryEl.textContent = lesson.summary || "";
  clearElement(lessonKeypointsEl);

  (lesson.key_points || []).forEach((kp) => {
    const li = document.createElement("li");
    li.textContent = kp;
    lessonKeypointsEl.appendChild(li);
  });

  clearElement(quizContentEl);
  const p = document.createElement("p");
  p.className = "muted small";
  p.textContent = 'Click "Quiz me on this lesson" to generate questions.';
  quizContentEl.appendChild(p);
}

/* API calls */

async function generatePlan() {
  const topic = topicInput.value.trim();
  const level = levelSelect.value;
  const tone = toneSelect.value;
  const goal = goalInput.value.trim();

  if (!topic || !goal) return;

  generateBtn.disabled = true;
  generateBtn.textContent = "Generating...";
  setBuilderStatus("Generating your mini-course...");

  try {
    const res = await fetch("/api/plan", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ topic, level, goal, tone }),
    });

    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error(data.error || `Request failed: ${res.status}`);
    }

    const data = await res.json();
    plan = data.plan;
    renderPlan();
    setBuilderStatus(
      "Course generated. You can tweak the form and regenerate anytime."
    );
  } catch (err) {
    console.error(err);
    setBuilderStatus(
      "Something went wrong generating the course. Please try again.",
      true
    );
  } finally {
    generateBtn.disabled = false;
    generateBtn.textContent = "Generate class";
  }
}

async function generateQuiz() {
  if (!plan || currentLessonIndex == null) return;
  const lesson = plan.lessons[currentLessonIndex];

  quizButton.disabled = true;
  const originalText = quizButton.textContent;
  quizButton.textContent = "Generating quiz...";

  clearElement(quizContentEl);
  const loadingP = document.createElement("p");
  loadingP.className = "muted small";
  loadingP.textContent = "Asking the tutor to create some questions...";
  quizContentEl.appendChild(loadingP);

  try {
    const res = await fetch("/api/quiz", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        lesson,
        topic: plan.topic,
        level: plan.level,
      }),
    });

    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error(data.error || `Request failed: ${res.status}`);
    }

    const data = await res.json();
    renderQuiz(data.questions || []);
  } catch (err) {
    console.error(err);
    clearElement(quizContentEl);
    const p = document.createElement("p");
    p.className = "muted small";
    p.textContent =
      "Couldn't generate quiz questions right now. Try again in a bit.";
    quizContentEl.appendChild(p);
  } finally {
    quizButton.disabled = false;
    quizButton.textContent = originalText;
  }
}

function renderQuiz(questions) {
  clearElement(quizContentEl);

  if (!questions.length) {
    const p = document.createElement("p");
    p.className = "muted small";
    p.textContent = "No quiz questions were generated.";
    quizContentEl.appendChild(p);
    return;
  }

  questions.forEach((q, idx) => {
    const div = document.createElement("div");
    div.className = "quiz-question";

    const h5 = document.createElement("h5");
    h5.textContent = `Q${idx + 1}. ${q.question || ""}`;
    div.appendChild(h5);

    if (q.type === "mcq" && Array.isArray(q.options) && q.options.length) {
      const ul = document.createElement("ul");
      ul.className = "keypoints";
      q.options.forEach((opt) => {
        const li = document.createElement("li");
        li.textContent = opt;
        ul.appendChild(li);
      });
      div.appendChild(ul);
    }

    const answerDiv = document.createElement("div");
    answerDiv.className = "answer";
    answerDiv.style.display = "none";
    answerDiv.innerHTML =
      `<strong>Answer:</strong> ${q.answer || "n/a"}<br>` +
      `<strong>Why:</strong> ${q.explanation || ""}`;
    div.appendChild(answerDiv);

    const btn = document.createElement("button");
    btn.type = "button";
    btn.textContent = "Show answer";
    btn.addEventListener("click", () => {
      const isHidden = answerDiv.style.display === "none";
      answerDiv.style.display = isHidden ? "block" : "none";
      btn.textContent = isHidden ? "Hide answer" : "Show answer";
    });
    div.appendChild(btn);

    quizContentEl.appendChild(div);
  });
}

async function sendChatMessage() {
  const text = chatInput.value.trim();
  if (!text) return;

  if (!plan) {
    addChatMessage(
      "assistant",
      "Generate a course first, then I'll tutor you on it."
    );
    return;
  }

  addChatMessage("user", text);
  conversation.push({ role: "user", content: text });
  chatInput.value = "";
  chatInput.disabled = true;
  chatSendBtn.disabled = true;

  const thinkingEl = document.createElement("div");
  thinkingEl.className = "chat-message assistant";
  thinkingEl.textContent = "Thinking...";
  chatMessagesEl.appendChild(thinkingEl);
  chatMessagesEl.scrollTop = chatMessagesEl.scrollHeight;

  try {
    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ messages: conversation, plan }),
    });

    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      throw new Error(data.error || `Request failed: ${res.status}`);
    }

    const data = await res.json();
    const reply = data.reply || "I couldn't come up with a response.";
    thinkingEl.remove();
    addChatMessage("assistant", reply);
    conversation.push({ role: "assistant", content: reply });
    speak(reply);
  } catch (err) {
    console.error(err);
    thinkingEl.remove();
    addChatMessage(
      "assistant",
      "Sorry, something went wrong on the server. Please try again."
    );
  } finally {
    chatInput.disabled = false;
    chatSendBtn.disabled = false;
    chatInput.focus();
  }
}

/* Event listeners */

builderForm.addEventListener("submit", (e) => {
  e.preventDefault();
  generatePlan();
});

quizButton.addEventListener("click", () => {
  generateQuiz();
});

chatForm.addEventListener("submit", (e) => {
  e.preventDefault();
  sendChatMessage();
});

// Voice mode wiring
if (voiceModeToggle) {
  // Disable toggle if no voice capability at all
  if (!supportsSpeechRecognition && !supportsSpeechSynthesis) {
    voiceModeToggle.disabled = true;
    voiceModeToggle.checked = false;
  }

  voiceModeToggle.addEventListener("change", (e) => {
    voiceModeEnabled = e.target.checked;

    if (!voiceModeEnabled) {
      if (speechRecognition && isListening) {
        try {
          speechRecognition.stop();
        } catch (_) {}
      }
      if (supportsSpeechSynthesis) {
        window.speechSynthesis.cancel();
      }
      if (micButton) {
        micButton.disabled = true;
        micButton.classList.remove("listening");
        micButton.textContent = "Mic";
      }
    } else {
      if (micButton) {
        micButton.disabled = !supportsSpeechRecognition;
      }
      if (!supportsSpeechRecognition && !supportsSpeechSynthesis) {
        alert(
          "Voice mode is not supported in this browser. Try Chrome or Edge."
        );
        voiceModeToggle.checked = false;
        voiceModeEnabled = false;
      }
    }
  });
}

if (micButton) {
  micButton.disabled = true; // enabled when voice mode is on and SR supported
  micButton.addEventListener("click", () => {
    toggleListening();
  });
}